Add support for paused subscriptions
android/play-billing-samples pull request #419
Opened 2021-02-03 00:29 UTC by cartland

2021-02-03 01:16 UTC, calren approved these changes
nice!!

2021-02-03 01:23 UTC, calren commented on ClassyTaxiJava/app/src/main/java/com/sample/android/classytaxijava/ui/BillingViewModel.java
> +     * OpenOpen the subscription page on Google Play.
small typo here

2021-02-03 13:31 UTC, pyman2 requested changes
Hi, Thanks for this, I'm just trying it out and I think we need to add this line to ClassyTaxiServer/src/play-billing/internal/purchases_impl.ts after line 156, as it is sending autoResumeTimeMillis to the app as a String:

    if (purchase.autoResumeTimeMillis) purchase.autoResumeTimeMillis = Number(purchase.autoResumeTimeMillis);

2021-02-03 19:47 UTC, cartland commented
@pyman2 thank you! Good catch. I also updated the UI to show the date when the subscription will resume, so now it will actually use the autoResumeTimeMillis instead of just passing it to the app without using it.

2021-02-03 19:47 UTC, cartland commented
@calren can you please take another look at the recent changes?

2021-02-04 02:23 UTC, calren commented
nice, lgtm. and thanks @pyman2 for catching that!

2021-02-04 19:56 UTC, merged

2021-02-06 12:09 UTC, pyman2 commented
@cartland Now I have autoResumeTimeMillis thanks to your code, I'm hoping to use it to see whether a pause is still upcoming or has been cancelled by the user, but the values it sends aren't what I would expect.  I've asked Google about it here: 
 https://issuetracker.google.com/u/1/issues/179463140

2021-02-11 18:07 UTC, cartland commented
@pyman2 thank you for submitted the information in the Issue Tracker! The engineering team will take a look at the details there.

2021-02-20 23:47 UTC, tata406 approved these changes